USE [Empresa]

IF OBJECT_ID('Funcionarios', 'U') IS NOT NULL
DROP TABLE Funcionarios
GO

CREATE TABLE Funcionarios (
Codigo INT NOT NULL PRIMARY KEY,
PrimeiroNome NVARCHAR(50) NOT NULL,
SegundoNome NVARCHAR(50) NOT NULL,
UltimoNome NVARCHAR(50) NOT NULL,
DataNasci DATE(8) NOT NULL,
CPF INT(11) NOT NULL,
RG INT(10) NOT NULL,
Endereco NVARCHAR(60) NOT NULL,
CEP INT(8) NOT NULL,
UF NVARCHAR(2) NOT NULL,
Telefone INT(14) NOT NULL,
Funcao NVARCHAR(30) NOT NULL,
Salario INT(5) NOT NULL
);
GO